### ISSUE TITLE
Add metadata to the ChangeSet

### ISSUE THREAD

**Issue by ewuerger** [DSD-DBS/capella-rm-bridge#39]
In order to know which model the calculated ChangeSet is for, which Capella version , which capellambse version and what revision, revision hash and branch (if versioned model) was used, this information should be included into the ChangeSet.

It should look like the following:
```yaml
capella: v6.0.0
title: Example
url: git@ssh.xyz/example.git
hash: 12345678...
branch: main
revision: HEAD
capellambse: 0.5.15
referencing: implicit
---
...
```

`referencing` will inform about the type of the ChangeSet. If `referencing: explicit` is set it is expected that the ChangeSet includes all implicit changes as well (actions to references).
